name: "CI Checks"
on: [pull_request]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Lint files
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test